version: '3.8'

services:
  backend:
    build:
      context: ./api-padel
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - frontend

  frontend:
    build:
      context: ./PADELVIVO
    ports:
      - "80:80"
