services:
  - type: web
    name: padelvivo-backend
    env: docker
    repo: https://github.com/VanessaObil/PadelVivo
    region: oregon
    plan: free
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DB_URL
        value: jdbc:mariadb://localhost:3306/padelvivo
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: rootroot
      - key: FRONTEND_URL_PROD
        value: https://padelvivo-app.onrender.com

  - type: web
    name: padelvivo-frontend
    env: docker
    repo: https://github.com/VanessaObil/PadelVivo
    region: oregon
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
