services:
  - type: web
    name: padelvivo-app
    env: docker
    repo: https://github.com/VanessaObil/PadelVivo
    branch: main
    region: oregon
    plan: free
    dockerComposeFilePath: ./docker-compose.yml
    envVars:
      - key: DB_URL
        value: jdbc:mariadb://mariadb:3308/PadelVivo
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: rootroot
