services:
  - type: docker
    name: padelvivo-app
    repo: https://github.com/VanessaObil/PadelVivo
    region: oregon
    plan: free
    dockerComposeFilePath: ./docker-compose.yml
    envVars:
      - key: DB_URL
        value: jdbc:mariadb://host:puerto/basededatos
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: rootroot
      - key: FRONTEND_URL_PROD
        value: https://padelvivo-app.onrender.com
